// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.4
// source: auth/auth.proto

package auth

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PgpData       []byte                 `protobuf:"bytes,1,opt,name=pgp_data,json=pgpData,proto3" json:"pgp_data,omitempty"`
	WebauthnData  []byte                 `protobuf:"bytes,2,opt,name=webauthn_data,json=webauthnData,proto3" json:"webauthn_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKey) Reset() {
	*x = PublicKey{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKey) ProtoMessage() {}

func (x *PublicKey) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKey.ProtoReflect.Descriptor instead.
func (*PublicKey) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *PublicKey) GetPgpData() []byte {
	if x != nil {
		return x.PgpData
	}
	return nil
}

func (x *PublicKey) GetWebauthnData() []byte {
	if x != nil {
		return x.WebauthnData
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *Identity) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RegisterPublicKeyRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	PublicKey *PublicKey             `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Identity  *Identity              `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// The role of the public key. When skip_user_role is true, this field is ignored.
	Role string `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	// If true, the role field will be used to determine the role of the public key.
	SkipUserRole  bool `protobuf:"varint,6,opt,name=skip_user_role,json=skipUserRole,proto3" json:"skip_user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPublicKeyRequest) Reset() {
	*x = RegisterPublicKeyRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyRequest) ProtoMessage() {}

func (x *RegisterPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterPublicKeyRequest) GetPublicKey() *PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterPublicKeyRequest) GetIdentity() *Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *RegisterPublicKeyRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RegisterPublicKeyRequest) GetSkipUserRole() bool {
	if x != nil {
		return x.SkipUserRole
	}
	return false
}

type RegisterPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginUrl      string                 `protobuf:"bytes,1,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	PublicKeyId   string                 `protobuf:"bytes,2,opt,name=public_key_id,json=publicKeyId,proto3" json:"public_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPublicKeyResponse) Reset() {
	*x = RegisterPublicKeyResponse{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPublicKeyResponse) ProtoMessage() {}

func (x *RegisterPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*RegisterPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterPublicKeyResponse) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

func (x *RegisterPublicKeyResponse) GetPublicKeyId() string {
	if x != nil {
		return x.PublicKeyId
	}
	return ""
}

type AwaitPublicKeyConfirmationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyId   string                 `protobuf:"bytes,1,opt,name=public_key_id,json=publicKeyId,proto3" json:"public_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AwaitPublicKeyConfirmationRequest) Reset() {
	*x = AwaitPublicKeyConfirmationRequest{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwaitPublicKeyConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwaitPublicKeyConfirmationRequest) ProtoMessage() {}

func (x *AwaitPublicKeyConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwaitPublicKeyConfirmationRequest.ProtoReflect.Descriptor instead.
func (*AwaitPublicKeyConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AwaitPublicKeyConfirmationRequest) GetPublicKeyId() string {
	if x != nil {
		return x.PublicKeyId
	}
	return ""
}

type ConfirmPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyId   string                 `protobuf:"bytes,1,opt,name=public_key_id,json=publicKeyId,proto3" json:"public_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmPublicKeyRequest) Reset() {
	*x = ConfirmPublicKeyRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmPublicKeyRequest) ProtoMessage() {}

func (x *ConfirmPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*ConfirmPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmPublicKeyRequest) GetPublicKeyId() string {
	if x != nil {
		return x.PublicKeyId
	}
	return ""
}

type RevokePublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyId   string                 `protobuf:"bytes,1,opt,name=public_key_id,json=publicKeyId,proto3" json:"public_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokePublicKeyRequest) Reset() {
	*x = RevokePublicKeyRequest{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokePublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokePublicKeyRequest) ProtoMessage() {}

func (x *RevokePublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokePublicKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokePublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RevokePublicKeyRequest) GetPublicKeyId() string {
	if x != nil {
		return x.PublicKeyId
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\"K\n" +
	"\tPublicKey\x12\x19\n" +
	"\bpgp_data\x18\x01 \x01(\fR\apgpData\x12#\n" +
	"\rwebauthn_data\x18\x02 \x01(\fR\fwebauthnData\" \n" +
	"\bIdentity\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"\xbc\x01\n" +
	"\x18RegisterPublicKeyRequest\x12.\n" +
	"\n" +
	"public_key\x18\x01 \x01(\v2\x0f.auth.PublicKeyR\tpublicKey\x12*\n" +
	"\bidentity\x18\x02 \x01(\v2\x0e.auth.IdentityR\bidentity\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12$\n" +
	"\x0eskip_user_role\x18\x06 \x01(\bR\fskipUserRoleJ\x04\b\x03\x10\x04J\x04\b\x04\x10\x05\"\\\n" +
	"\x19RegisterPublicKeyResponse\x12\x1b\n" +
	"\tlogin_url\x18\x01 \x01(\tR\bloginUrl\x12\"\n" +
	"\rpublic_key_id\x18\x02 \x01(\tR\vpublicKeyId\"G\n" +
	"!AwaitPublicKeyConfirmationRequest\x12\"\n" +
	"\rpublic_key_id\x18\x01 \x01(\tR\vpublicKeyId\"=\n" +
	"\x17ConfirmPublicKeyRequest\x12\"\n" +
	"\rpublic_key_id\x18\x01 \x01(\tR\vpublicKeyId\"<\n" +
	"\x16RevokePublicKeyRequest\x12\"\n" +
	"\rpublic_key_id\x18\x01 \x01(\tR\vpublicKeyId2\xd6\x02\n" +
	"\vAuthService\x12T\n" +
	"\x11RegisterPublicKey\x12\x1e.auth.RegisterPublicKeyRequest\x1a\x1f.auth.RegisterPublicKeyResponse\x12]\n" +
	"\x1aAwaitPublicKeyConfirmation\x12'.auth.AwaitPublicKeyConfirmationRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x10ConfirmPublicKey\x12\x1d.auth.ConfirmPublicKeyRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0fRevokePublicKey\x12\x1c.auth.RevokePublicKeyRequest\x1a\x16.google.protobuf.EmptyB1Z/github.com/siderolabs/go-api-signature/api/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_auth_auth_proto_goTypes = []any{
	(*PublicKey)(nil),                         // 0: auth.PublicKey
	(*Identity)(nil),                          // 1: auth.Identity
	(*RegisterPublicKeyRequest)(nil),          // 2: auth.RegisterPublicKeyRequest
	(*RegisterPublicKeyResponse)(nil),         // 3: auth.RegisterPublicKeyResponse
	(*AwaitPublicKeyConfirmationRequest)(nil), // 4: auth.AwaitPublicKeyConfirmationRequest
	(*ConfirmPublicKeyRequest)(nil),           // 5: auth.ConfirmPublicKeyRequest
	(*RevokePublicKeyRequest)(nil),            // 6: auth.RevokePublicKeyRequest
	(*emptypb.Empty)(nil),                     // 7: google.protobuf.Empty
}
var file_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.RegisterPublicKeyRequest.public_key:type_name -> auth.PublicKey
	1, // 1: auth.RegisterPublicKeyRequest.identity:type_name -> auth.Identity
	2, // 2: auth.AuthService.RegisterPublicKey:input_type -> auth.RegisterPublicKeyRequest
	4, // 3: auth.AuthService.AwaitPublicKeyConfirmation:input_type -> auth.AwaitPublicKeyConfirmationRequest
	5, // 4: auth.AuthService.ConfirmPublicKey:input_type -> auth.ConfirmPublicKeyRequest
	6, // 5: auth.AuthService.RevokePublicKey:input_type -> auth.RevokePublicKeyRequest
	3, // 6: auth.AuthService.RegisterPublicKey:output_type -> auth.RegisterPublicKeyResponse
	7, // 7: auth.AuthService.AwaitPublicKeyConfirmation:output_type -> google.protobuf.Empty
	7, // 8: auth.AuthService.ConfirmPublicKey:output_type -> google.protobuf.Empty
	7, // 9: auth.AuthService.RevokePublicKey:output_type -> google.protobuf.Empty
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
